apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-api
  template:
    metadata:
      labels:
        app: medical-api
    spec:
      containers:
      - name: medical-api
        image: medical-api:v1
        env:
        - name: DATABASE_URL
          value: postgresql+psycopg://user:password@postgres-service:5432/medical_db
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
